networks:
  data_network:
    driver: bridge

volumes:
  postgres_data:

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    networks:
      - data_network
    environment:
      POSTGRES_USER: licia
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: pipeline_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.1
    container_name: airflow_init
    networks:
      - data_network
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://licia:password123@postgres/pipeline_db
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Licia --lastname Attouche --role Admin --email attouche.licia@gmail.com"
    depends_on:
      - postgres

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow_webserver
    networks:
      - data_network
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://licia:password123@postgres/pipeline_db
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    command: airflow webserver
    depends_on:
      - postgres
      - airflow-init

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow_scheduler
    networks:
      - data_network
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://licia:password123@postgres/pipeline_db
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    command: airflow scheduler
    depends_on:
      - postgres
      - airflow-init